Traceback (most recent call last):
  File "c:\AppsPy\mtdcovabm\simulator\contactnetwork_mp.py", line 72, in contactnetwork_worker
    contact_network_util.simulate_contact_network(day, weekday)
  File "c:\AppsPy\mtdcovabm\simulator\contactnetwork.py", line 77, in simulate_contact_network
    cell_agents_directcontacts, cell = self.simulate_contact_network_by_cellid(cellid, day)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\AppsPy\mtdcovabm\simulator\contactnetwork.py", line 106, in simulate_contact_network_by_cellid
    self.epi_util.simulate_direct_contacts(agents_directcontacts, cellid, cell, day)
  File "c:\AppsPy\mtdcovabm\simulator\epidemiology.py", line 182, in simulate_direct_contacts
    agent_state_transition_by_day, recovered = self.simulate_seir_state_transition(exposed_agent_id, incremental_days, overlapping_timesteps, agent_state_transition_by_day, agent_epi_age_bracket_index, agent_quarantine_days)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\AppsPy\mtdcovabm\simulator\epidemiology.py", line 329, in simulate_seir_state_transition
    _, _ = self.schedule_quarantine(exposed_agent_id, start_quarantine_day, sampled_timestep, QuarantineType.Positive, quarantine_days=agent_quarantine_days)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\AppsPy\mtdcovabm\simulator\epidemiology.py", line 414, in schedule_quarantine
    self.agents_mp.set_shm(agent_id, "quarantine_days", quarantine_days)
  File "c:\AppsPy\mtdcovabm\simulator\agents.py", line 295, in set_shm
    self.quarantine_days[0][index] = value
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
TypeError: 'NoneType' object does not support item assignment
